services:
  # Frontend React + Vite (porta interna)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-}
        - VITE_API_URL=http://72.60.10.108:${FRONTEND_PORT:-3050}/api
        - VITE_APP_NAME=Ferraco CRM
    container_name: ferraco-frontend
    restart: unless-stopped
    # Sem portas expostas - acesso via proxy
    environment:
      - NODE_ENV=production
    networks:
      - ferraco-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend Node.js + Prisma + SQLite (porta interna)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-}
    container_name: ferraco-backend
    restart: unless-stopped
    # Sem portas expostas - acesso via proxy
    volumes:
      # Database volume para persistência (bind mount para garantir acesso)
      - ./backend/data:/app/data
      # Uploads volume para arquivos
      - backend-uploads:/app/uploads
      # Logs volume para debugging
      - backend-logs:/app/logs
      # Arquivo de ambiente de produção
      - ./backend/.env.production:/app/.env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=file:./data/ferraco.db
      - JWT_SECRET=${JWT_SECRET:-ferraco-default-jwt-secret}
      - JWT_EXPIRES_IN=7d
      - CORS_ORIGIN=http://72.60.10.108:3050,http://localhost:3000,http://localhost:5173
    networks:
      - ferraco-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Nginx Reverse Proxy (PONTO DE ENTRADA ÚNICO)
  proxy:
    image: nginx:alpine
    container_name: ferraco-proxy
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3050}:80"  # Porta principal da aplicação
    volumes:
      # Configuração do nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - ferraco-network
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Backup automático (opcional)
  backup:
    image: alpine:latest
    container_name: ferraco-backup
    restart: "no"
    volumes:
      - ./backend/data:/source/data:ro
      - ./backend/uploads:/source/uploads:ro
      - ./backups:/backups
    command: >
      sh -c "
        apk add --no-cache sqlite &&
        mkdir -p /backups &&
        TIMESTAMP=$$(date +%Y%m%d_%H%M%S) &&
        sqlite3 /source/data/ferraco.db \".backup /backups/ferraco_$$TIMESTAMP.db\" &&
        tar -czf /backups/uploads_$$TIMESTAMP.tar.gz -C /source uploads &&
        echo \"Backup completo: $$TIMESTAMP\" &&
        find /backups -name '*.db' -mtime +30 -delete &&
        find /backups -name '*.tar.gz' -mtime +30 -delete
      "
    networks:
      - ferraco-network
    profiles:
      - backup

# Rede interna para comunicação entre containers
networks:
  ferraco-network:
    driver: bridge
    name: ferraco-crm

# Volumes nomeados para backup fácil
volumes:
  backend-data:
    driver: local
  backend-uploads:
    driver: local
  backend-logs:
    driver: local