name: Test Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Echo
        run: |
          echo "GitHub Actions está funcionando!"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
